server:
  port: ${PORT:8761}

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:https://back-end-eureka-kmoa.onrender.com}
  server:
    renewal-percent-threshold: 0.90
